sudo: required
language: android
jdk: oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - DEFAULT_JVM_OPTS="-Dfile.encoding=UTF-8"
  - ANDROID_API=26
  - ANDROID_BUILD_TOOLS_VERSION=26.0.3
  - ADB_INSTALL_TIMEOUT=10
  - QEMU_AUDIO_DRV=none
  - DEPLOYGATE_USER=meronmks
  - secure: "XUYo9QZufYJ6k15D6OXRh2UDrlEfmijcvTqgj68dCtw5Dj4RWPgHqpzT8VaPaWlODWcGtwg/WK6wQ5S6Ip8iUguXS/uWMgrxlzUVi+ZCnFb9OQ3YFGQip7+jW8g6BPu7aPI+U3Z9SMja94v5HxE0TkXl7sy8Qnur7dnaWVPO3hkN52pYL/A1zvr26/2mx1JQt4RTgE/9lD/Abgf63QnyqphnOZ73iH2+ZFoj6wtEfiNfNCrfLQnaiXSKrBk5IJIHjP0GAHKAHEH5z/m4YQhE7ixrD+RijgxzArfGibl/sCLG2p2L0wno1sMz7TuqbG/pFePYjUxc3hYCamjGCnqvJtx7gw8o6hbq/aERWwMvoeEWnR6NETPd2SSb5+76SM0v+hRri+vdvoOsE4H9+v5mlIIWZmHtKDWXWzfM8V6tWmLSCxTkHTqHmcnmGWJyAgLZItPyoFUuDaaFVQWYo/LnQzfVXKR4ateCe9pG5uE/PkEJt8nb4lnYgFJ99jPeab4zPxfgoycFk+fuczbi9KxSngLh5Hdbo0Y5W/brFapiRCVoyjiuK8P2pjXrL3LA/L2KlndaDXeV800alO3UDxIv6+BnGDngxz4x5G7b/v/6cbiyHDhmhAIM1hsjy7GHUSPbC1ciMjNu52WgZDe5EpXNy9JpEICjCZ1L6szbJ+Or22s="
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API
  - android-22
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-android-22
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
install:
  # Update sdk tools to latest version and install/update components
  - echo no | sdkmanager "tools"
  - echo no | sdkmanager "platforms;android-$ANDROID_API" # Latest platform required by SDK tools
  - echo no | sdkmanager "extras;android;m2repository"
  - echo no | sdkmanager "extras;google;m2repository"
  - echo no | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo no | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

script:
  - ./gradlew assembleDebug test
  - ./gradlew jacocoTestDebugUnitTestCoverage
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew uploadDeployGateDevelopDebug
notifications:
  slack:
    secure: mzQNR8KamIy41sfrrdeCP2XcA5+jngPdpeJYyC8KSoyBdpLGNJg4vp5fYkLKVAr9AJU9N1vi/tmaEnVhVuvEZlWd8ce46rXYoh8IH5ODgCvFn9KqePBpfq9cPaoJRsmWzaK+oqyHvz19hPHSGuUW5+Op+Mglxcod5t0kJH+nrmpnRepu6Az9h+P1M2dQYi94Ma7aDXHEFROssPqUk299efcWT/DSp6PpAokREJap1MW862Ay8YdxQZGX/tnlihtfapHB+NYnCorCvyiMrSveqrG4r6/7WxyD41VG1gmxurDNi0xxMnPyNnbOO8nXYTddJG5dlsuL45bIM5BHXIBWSJm6SyVysKU0A3raOzEYfBYrPg683g3Sc8K/88UtRmCAQZmDvtnBseZMcVYqOzOsKPYD/JeFYjiIH1R4FtghSFjdbmnhZk3iNgRuzlnjgEmu2cF93VA7qYhq/RAzKr1sZWj5H6l9ieG2yij50MawQ2HT3Ki3Y/0BCCshHdrdXHNICavcwcU0bHZ0lJ2MG4wmaxJMn45R23PQ7mrrBkrbE9uO0wlJYu9Z6iF40iR+i5rE2emC8HJw6PvKJ4Qae+qPdsFt9d/W8aOqx4PvfO8/pG7FsZO6wrJJLJcs2GqDShgT5gtlYeMEJ0d0bkOyM286IhBN0pDtrrkL6hQ7TNvTexI=
  email: false