language: android
jdk: oraclejdk8
android:
  components:
    - tools # to get the new 'repository-11.xml'
    - platform-tools

    # The BuildTools version used by project
    - build-tools-27.0.3

    # The SDK version used to compile project
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

install:
  # Update sdk tools to latest version and install/update components
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-26" # Latest platform required by SDK tools
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
