sudo: false
language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=26.0.3
  - ANDROID_EMU_API_LEVEL=25
  - ANDROID_ABI=armeabi-v7a
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - ADB_INSTALL_TIMEOUT=20
  - QEMU_AUDIO_DRV=none
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMU_API_LEVEL
  - extra-android-support
script:
  - "./gradlew build test"
  - "./gradlew assembleDebug test"
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: mzQNR8KamIy41sfrrdeCP2XcA5+jngPdpeJYyC8KSoyBdpLGNJg4vp5fYkLKVAr9AJU9N1vi/tmaEnVhVuvEZlWd8ce46rXYoh8IH5ODgCvFn9KqePBpfq9cPaoJRsmWzaK+oqyHvz19hPHSGuUW5+Op+Mglxcod5t0kJH+nrmpnRepu6Az9h+P1M2dQYi94Ma7aDXHEFROssPqUk299efcWT/DSp6PpAokREJap1MW862Ay8YdxQZGX/tnlihtfapHB+NYnCorCvyiMrSveqrG4r6/7WxyD41VG1gmxurDNi0xxMnPyNnbOO8nXYTddJG5dlsuL45bIM5BHXIBWSJm6SyVysKU0A3raOzEYfBYrPg683g3Sc8K/88UtRmCAQZmDvtnBseZMcVYqOzOsKPYD/JeFYjiIH1R4FtghSFjdbmnhZk3iNgRuzlnjgEmu2cF93VA7qYhq/RAzKr1sZWj5H6l9ieG2yij50MawQ2HT3Ki3Y/0BCCshHdrdXHNICavcwcU0bHZ0lJ2MG4wmaxJMn45R23PQ7mrrBkrbE9uO0wlJYu9Z6iF40iR+i5rE2emC8HJw6PvKJ4Qae+qPdsFt9d/W8aOqx4PvfO8/pG7FsZO6wrJJLJcs2GqDShgT5gtlYeMEJ0d0bkOyM286IhBN0pDtrrkL6hQ7TNvTexI=
  email: false