sudo: false
language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=26.0.3
  - ANDROID_ABI=google_apis/armeabi-v7a
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - ADB_INSTALL_TIMEOUT=20
  - QEMU_AUDIO_DRV=none
  - DEPLOYGATE_USER=meronmks
  - secure: "XUYo9QZufYJ6k15D6OXRh2UDrlEfmijcvTqgj68dCtw5Dj4RWPgHqpzT8VaPaWlODWcGtwg/WK6wQ5S6Ip8iUguXS/uWMgrxlzUVi+ZCnFb9OQ3YFGQip7+jW8g6BPu7aPI+U3Z9SMja94v5HxE0TkXl7sy8Qnur7dnaWVPO3hkN52pYL/A1zvr26/2mx1JQt4RTgE/9lD/Abgf63QnyqphnOZ73iH2+ZFoj6wtEfiNfNCrfLQnaiXSKrBk5IJIHjP0GAHKAHEH5z/m4YQhE7ixrD+RijgxzArfGibl/sCLG2p2L0wno1sMz7TuqbG/pFePYjUxc3hYCamjGCnqvJtx7gw8o6hbq/aERWwMvoeEWnR6NETPd2SSb5+76SM0v+hRri+vdvoOsE4H9+v5mlIIWZmHtKDWXWzfM8V6tWmLSCxTkHTqHmcnmGWJyAgLZItPyoFUuDaaFVQWYo/LnQzfVXKR4ateCe9pG5uE/PkEJt8nb4lnYgFJ99jPeab4zPxfgoycFk+fuczbi9KxSngLh5Hdbo0Y5W/brFapiRCVoyjiuK8P2pjXrL3LA/L2KlndaDXeV800alO3UDxIv6+BnGDngxz4x5G7b/v/6cbiyHDhmhAIM1hsjy7GHUSPbC1ciMjNu52WgZDe5EpXNy9JpEICjCZ1L6szbJ+Or22s="
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMU_API_LEVEL
  - extra-android-support
  - sys-img-armeabi-v7a-addon-google_apis-google-25
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew assembleDebug test
  - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew uploadDeployGateDevelopDebug
notifications:
  slack:
    secure: mzQNR8KamIy41sfrrdeCP2XcA5+jngPdpeJYyC8KSoyBdpLGNJg4vp5fYkLKVAr9AJU9N1vi/tmaEnVhVuvEZlWd8ce46rXYoh8IH5ODgCvFn9KqePBpfq9cPaoJRsmWzaK+oqyHvz19hPHSGuUW5+Op+Mglxcod5t0kJH+nrmpnRepu6Az9h+P1M2dQYi94Ma7aDXHEFROssPqUk299efcWT/DSp6PpAokREJap1MW862Ay8YdxQZGX/tnlihtfapHB+NYnCorCvyiMrSveqrG4r6/7WxyD41VG1gmxurDNi0xxMnPyNnbOO8nXYTddJG5dlsuL45bIM5BHXIBWSJm6SyVysKU0A3raOzEYfBYrPg683g3Sc8K/88UtRmCAQZmDvtnBseZMcVYqOzOsKPYD/JeFYjiIH1R4FtghSFjdbmnhZk3iNgRuzlnjgEmu2cF93VA7qYhq/RAzKr1sZWj5H6l9ieG2yij50MawQ2HT3Ki3Y/0BCCshHdrdXHNICavcwcU0bHZ0lJ2MG4wmaxJMn45R23PQ7mrrBkrbE9uO0wlJYu9Z6iF40iR+i5rE2emC8HJw6PvKJ4Qae+qPdsFt9d/W8aOqx4PvfO8/pG7FsZO6wrJJLJcs2GqDShgT5gtlYeMEJ0d0bkOyM286IhBN0pDtrrkL6hQ7TNvTexI=
  email: false